### ISSUE TITLE
npm page's instruction has wrong.

### ISSUE THREAD

**Issue by kyasbal** [Makio64/shader-loader#1]
![image](https://cloud.githubusercontent.com/assets/6434708/7676609/36f9eeee-fcfa-11e4-9317-3cdf7bd0d443.png)

shader:{
   chunkPath:""
}

it should be

glsl:{
   chunkPath:""
}

or job will be failed.

**Comment by Makio64** [comment]
Thanks to signal this issue! fixed :)
